# define list of repos
# $releasever and $basearch will be replaced when doing build
[repo]
    standard_repos=["google-chrome", "nvidia", "vscode"]

[package]
    [package.rpm]
    install=[
        "moreutils",
        "gnome-terminal"
    ]

    [package.rpm_group]
    install=[
        "multimedia",
        "sound-and-video"
    ]

    remove=[
        "virtualization"
    ]