[repo]
    # common popular repos for convenience
    # can be any value of "google-chrome", "nvidia", "vscode"
    # default: emtpy
    standard_repos=[, "vscode"]

    # can be any copr repos in format of user_name/repo_name
    # default: emtpy
    copr_repos=["khoitd1997/toml11"]